### ISSUE TITLE
mac环境debug时出现的问题

### ISSUE THREAD

**Issue by hhhchenlu** [DoctorQ/CrashMonkey4Android#12]
你好，我mac环境debug报这个错误，请问下怎么解决
08-31 15:43:21 I/CommandScheduler: Enter isShutdown...
Using commandline arguments as starting command: [run, cts, --plan, Monkey, --p, com.pingan.papd, --a, com.pingan.papd.ui.activities.JKLogoActivity]
08-31 15:43:21 I/ConfigurationFactory: Loading configuration 'cts'
08-31 15:43:21 I/DeviceStateMonitor: Waiting 30000 ms for device c410c01 shell to be responsive
08-31 15:43:21 I/DeviceManager: Detected new device c410c01
08-31 15:43:21 I/ManagedDeviceListener: Device connected c410c01
08-31 15:43:22 I/CommandScheduler: cmd is not null...
08-31 15:43:22 I/DeviceManager: Allocated device c410c01
08-31 15:43:22 I/CommandScheduler: device: com.android.tradefed.device.TestDevice@52fb6f03
08-31 15:43:22 I/CommandScheduler: device is not null...
08-31 15:43:22 I/CommandScheduler: cmd is not loop mode...
08-31 15:43:22 I/CommandScheduler: Enter isShutdown...
08-31 15:43:22 I/TestInvocation: setup: true tearDown: true
08-31 15:43:22 I/TestInvocation: Starting invocation for 'cts' on build '4.4_r0' on device c410c01
08-31 15:43:22 I/MonkeyTest: Monkey Test for device c410c01
08-31 15:43:22 I/MonkeyTest: Attempting to launch com.pingan.papd on c410c01 using command [am start com.pingan.papd/com.pingan.papd.ui.activities.JKLogoActivity] 
08-31 15:43:22 I/MonkeyTest: Open monkey logcat for c410c01 .
java.io.IOException: Cannot run program "dumpsys": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at com.android.cts.tradefed.testtype.monkey.Monkey.getDeviceWidthAndHeight(Monkey.java:144)
	at com.android.cts.tradefed.testtype.monkey.Monkey.init(Monkey.java:119)
	at com.android.cts.tradefed.testtype.monkey.Monkey.<init>(Monkey.java:42)
	at com.android.cts.tradefed.testtype.MonkeyTest.run(MonkeyTest.java:171)
	at com.android.tradefed.invoker.TestInvocation.runTests(TestInvocation.java:628)
	at com.android.tradefed.invoker.TestInvocation.prepareAndRun(TestInvocation.java:433)
	at com.android.tradefed.invoker.TestInvocation.performInvocation(TestInvocation.java:360)
	at com.android.tradefed.invoker.TestInvocation.invoke(TestInvocation.java:142)
	at com.android.tradefed.command.CommandScheduler$InvocationThread.run(CommandScheduler.java:364)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 12 more
java.net.SocketException: Broken pipe (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
	at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:282)
	at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
	at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207)
	at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129)

**Comment by DoctorQ** [comment]
执行` adb shell dumpsys` 看看输出

**Comment by hhhchenlu** [comment]
还有发现执行过程中中断然后再重新执行就会报错

**Comment by hhhchenlu** [comment]
你好，运行的时候经常会出现broken pipe(write failed)的报错，想问下是什么原因

**Comment by hhhchenlu** [comment]
执行monkey时中断后再次执行就会报socketexception的错误，这个和手机里面有没杀死的monkey进程有关系吗？我看是chimpManager里面的方法报的错
