### ISSUE TITLE
monkey执行了一段时间后，socket连接异常

### ISSUE THREAD

**Issue by ahhswangkai** [DoctorQ/CrashMonkey4Android#5]
Error sending drag start event
java.net.SocketException: Broken pipe
    at java.net.SocketOutputStream.socketWrite0(Native Method)
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
    at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
    at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:282)
    at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
    at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207)
    at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129)
    at java.io.BufferedWriter.write(BufferedWriter.java:230)
    at java.io.Writer.write(Writer.java:157)
    at com.android.chimpchat.ChimpManager.sendMonkeyEventAndGetResponse(ChimpManager.java:186)
    at com.android.chimpchat.ChimpManager.sendMonkeyEvent(ChimpManager.java:235)
    at com.android.chimpchat.ChimpManager.touchMove(ChimpManager.java:112)
    at com.android.chimpchat.adb.AdbChimpDevice$2.step(AdbChimpDevice.java:560)
    at com.android.chimpchat.adb.LinearInterpolator.interpolate(LinearInterpolator.java:123)
    at com.android.chimpchat.adb.AdbChimpDevice.drag(AdbChimpDevice.java:556)
    at com.android.cts.tradefed.testtype.monkey.MonkeyDragEvent.fireEvent(MonkeyDragEvent.java:39)
    at com.android.cts.tradefed.testtype.monkey.Monkey.nextRandomEvent(Monkey.java:41)
    at com.android.cts.tradefed.testtype.MonkeyTest.run(MonkeyTest.java:152)
    at com.android.tradefed.invoker.TestInvocation.runTests(TestInvocation.java:590)
    at com.android.tradefed.invoker.TestInvocation.prepareAndRun(TestInvocation.java:400)
    at com.android.tradefed.invoker.TestInvocation.performInvocation(TestInvocation.java:332)
    at com.android.tradefed.invoker.TestInvocation.invoke(TestInvocation.java:133)
    at com.android.tradefed.command.CommandScheduler$InvocationThread.run(CommandScheduler.java:362)

**Comment by DoctorQ** [comment]
monkey用的是chimpchat这个包，这个问题是这个包包出去来的，是adb通信出现了问题，暂时的解决方法是重启一下手机再跑，试图修复过这个问题，没解决，争取后续看看有什么替代方案，抱歉
