### ISSUE TITLE
执行cts-tradefed.bat，cmd里显示如下，请问我的系统是64位，这个可执行文件兼容64位么？

### ISSUE THREAD

**Issue by azdbaaaaaa** [DoctorQ/CrashMonkey4Android#6]
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\zhoudonbin\A
ppData\Local\Temp\jline_0_9_9.dll: Can't load IA 32-bit .dll on a AMD 64-bit pla
tform
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1851)
        at java.lang.Runtime.load0(Runtime.java:795)
        at java.lang.System.load(System.java:1062)
        at jline.WindowsTerminal.loadLibrary(WindowsTerminal.java:215)
        at jline.WindowsTerminal.initializeTerminal(WindowsTerminal.java:144)
        at jline.Terminal.setupTerminal(Terminal.java:69)
        at jline.Terminal.getTerminal(Terminal.java:26)
        at jline.ConsoleReader.<init>(ConsoleReader.java:151)
        at jline.ConsoleReader.<init>(ConsoleReader.java:146)
        at jline.ConsoleReader.<init>(ConsoleReader.java:135)
        at com.android.tradefed.command.Console.getReader(Console.java:186)
        at com.android.tradefed.command.Console.<init>(Console.java:198)
        at com.android.cts.tradefed.command.CtsConsole.<init>(CtsConsole.java:52
)
        at com.android.cts.tradefed.command.CtsConsole.main(CtsConsole.java:249)

请按任意键继续. . .

**Comment by zmywly8866** [comment]
同问

**Comment by smalpple** [comment]
+1

**Comment by limzhang** [comment]
同问，上面两楼的同仁解决了吗
